apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "audiomuse-ai.fullname" . }}-config
  namespace: {{ .Release.Namespace }} # Use .Release.Namespace
  labels:
    {{- include "audiomuse-ai.labels" . | nindent 4 }}
data:
  # General Constants (Essential)
  JELLYFIN_URL: {{ .Values.jellyfin.url | quote }}
  TEMP_DIR: {{ .Values.config.tempDir | quote }}
  MAX_DISTANCE: {{ printf "%v" (.Values.config.maxDistance | default 0.5) | quote }}
  MAX_SONGS_PER_CLUSTER: {{ printf "%v" (.Values.config.maxSongsPerCluster | default 0) | quote }}
  MAX_SONGS_PER_ARTIST: {{ printf "%v" (.Values.config.maxSongsPerArtist | default 3) | quote }}
  NUM_RECENT_ALBUMS: {{ printf "%v" (.Values.config.numRecentAlbums | default 0) | quote }}

  # Algorithm Choose Constants (Essential for runtime switching)
  CLUSTER_ALGORITHM: {{ .Values.config.clusterAlgorithm | quote }}
  AI_MODEL_PROVIDER: {{ .Values.config.aiModelProvider | quote }}
  ENABLE_CLUSTERING_EMBEDDINGS: {{ printf "%v" (.Values.config.enableClusteringEmbeddings | default false) | quote }}

  # AI Playlist Naming (Essential URLs/Models)
  OLLAMA_SERVER_URL: {{ .Values.config.ollamaServerUrl | quote }}
  OLLAMA_MODEL_NAME: {{ .Values.config.ollamaModelName | quote }}
  GEMINI_MODEL_NAME: {{ .Values.config.geminiModelName | quote }}

  # DB Host/Port/URL for Postgres and Redis (Derived from service names)
  POSTGRES_HOST: {{ printf "%s-postgres" (include "audiomuse-ai.fullname" .) }}
  POSTGRES_PORT: {{ .Values.postgres.service.port | quote }}
  REDIS_URL: {{ printf "redis://%s-redis:%d/0" (include "audiomuse-ai.fullname" .) .Values.redis.service.port }}

  # AI User for Chat SQL Execution (Essential)
  AI_CHAT_DB_USER_NAME: {{ .Values.config.aiChatDbUserName | quote }}