apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "audiomuse-ai.fullname" . }}-env-vars
  labels:
    {{- include "audiomuse-ai.labels" . | nindent 4 }}
data:
  TZ: {{ .Values.timezone | default "UTC" | quote }}

  {{- if .Values.postgres.enabled }}
  POSTGRES_HOST: {{ printf "%s-postgres" (include "audiomuse-ai.fullname" .) }}
  POSTGRES_PORT: {{ int .Values.postgres.service.port | quote }}
  {{- else }}
  POSTGRES_HOST: {{ required "postgres.external.host must be set when postgres.enabled=false" .Values.postgres.external.host | quote }}
  POSTGRES_PORT: {{ int .Values.postgres.external.port | quote }}
  {{- end }}
  {{- if .Values.redis.enabled }}
  REDIS_URL: "redis://{{ include "audiomuse-ai.fullname" . }}-redis:{{ .Values.redis.service.port }}/0"
  {{- else }}
  REDIS_URL: {{ required "redis.external.url must be set when redis.enabled=false" .Values.redis.external.url | quote }}
  {{- end }}