apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "audiomuse-ai.fullname" . }}-config
  namespace: {{ .Release.Namespace }} # Use .Release.Namespace
  labels:
    {{- include "audiomuse-ai.labels" . | nindent 4 }}
data:
  # General Constants
  JELLYFIN_URL: {{ .Values.jellyfin.url | quote }}
  TEMP_DIR: {{ .Values.config.tempDir | quote }}
  MAX_DISTANCE: {{ printf "%v" .Values.config.maxDistance | quote }}
  MAX_SONGS_PER_CLUSTER: {{ printf "%v" .Values.config.maxSongsPerCluster | quote }}
  MAX_SONGS_PER_ARTIST: {{ printf "%v" .Values.config.maxSongsPerArtist | quote }}
  NUM_RECENT_ALBUMS: {{ printf "%v" .Values.config.numRecentAlbums | quote }}

  # Algorithm Choose Constants
  CLUSTER_ALGORITHM: {{ .Values.config.clusterAlgorithm | quote }}
  AI_MODEL_PROVIDER: {{ .Values.config.aiModelProvider | quote }}
  ENABLE_CLUSTERING_EMBEDDINGS: {{ printf "%v" .Values.config.enableClusteringEmbeddings | quote }}

  # DBSCAN Only Constants
  DBSCAN_EPS_MIN: {{ printf "%v" .Values.config.dbscanEpsMin | quote }}
  DBSCAN_EPS_MAX: {{ printf "%v" .Values.config.dbscanEpsMax | quote }}
  DBSCAN_MIN_SAMPLES_MIN: {{ printf "%v" .Values.config.dbscanMinSamplesMin | quote }}
  DBSCAN_MIN_SAMPLES_MAX: {{ printf "%v" .Values.config.dbscanMinSamplesMax | quote }}

  # KMEANS Only Constants
  NUM_CLUSTERS_MIN: {{ printf "%v" .Values.config.numClustersMin | quote }}
  NUM_CLUSTERS_MAX: {{ printf "%v" .Values.config.numClustersMax | quote }}
  USE_MINIBATCH_KMEANS: {{ printf "%v" .Values.config.useMinibatchKmeans | quote }}
  MINIBATCH_KMEANS_PROCESSING_BATCH_SIZE: {{ printf "%v" .Values.config.minibatchKmeansProcessingBatchSize | quote }}

  # GMM Only Constants
  GMM_N_COMPONENTS_MIN: {{ printf "%v" .Values.config.gmmNComponentsMin | quote }}
  GMM_N_COMPONENTS_MAX: {{ printf "%v" .Values.config.gmmNComponentsMax | quote }}
  GMM_COVARIANCE_TYPE: {{ .Values.config.gmmCovarianceType | quote }}

  # PCA Constants
  PCA_COMPONENTS_MIN: {{ printf "%v" .Values.config.pcaComponentsMin | quote }}
  PCA_COMPONENTS_MAX: {{ printf "%v" .Values.config.pcaComponentsMax | quote }}

  # Clustering Runs for Diversity
  CLUSTERING_RUNS: {{ printf "%v" .Values.config.clusteringRuns | quote }}
  MAX_QUEUED_ANALYSIS_JOBS: {{ printf "%v" .Values.config.maxQueuedAnalysisJobs | quote }}

  # Batching Constants for Clustering Runs
  ITERATIONS_PER_BATCH_JOB: {{ printf "%v" .Values.config.iterationsPerBatchJob | quote }}
  MAX_CONCURRENT_BATCH_JOBS: {{ printf "%v" .Values.config.maxConcurrentBatchJobs | quote }}
  DB_FETCH_CHUNK_SIZE: {{ printf "%v" .Values.config.dbFetchChunkSize | quote }}

  # Guided Evolutionary Clustering Constants
  TOP_N_ELITES: {{ printf "%v" .Values.config.topNElites | quote }}
  EXPLOITATION_START_FRACTION: {{ printf "%v" .Values.config.exploitationStartFraction | quote }}
  EXPLOITATION_PROBABILITY: {{ printf "%v" .Values.config.exploitationProbability | quote }}
  MUTATION_INT_ABS_DELTA: {{ printf "%v" .Values.config.mutationIntAbsDelta | quote }}
  MUTATION_FLOAT_ABS_DELTA: {{ printf "%v" .Values.config.mutationFloatAbsDelta | quote }}
  MUTATION_KMEANS_COORD_FRACTION: {{ printf "%v" .Values.config.mutationKmeansCoordFraction | quote }}

  # Scoring Weights for Enhanced Diversity Score
  SCORE_WEIGHT_DIVERSITY: {{ printf "%v" .Values.config.scoreWeightDiversity | quote }}
  SCORE_WEIGHT_PURITY: {{ printf "%v" .Values.config.scoreWeightPurity | quote }}
  SCORE_WEIGHT_OTHER_FEATURE_DIVERSITY: {{ printf "%v" .Values.config.scoreWeightOtherFeatureDiversity | quote }}
  SCORE_WEIGHT_OTHER_FEATURE_PURITY: {{ printf "%v" .Values.config.scoreWeightOtherFeaturePurity | quote }}
  SCORE_WEIGHT_SILHOUETTE: {{ printf "%v" .Values.config.scoreWeightSilhouette | quote }}
  SCORE_WEIGHT_DAVIES_BOULDIN: {{ printf "%v" .Values.config.daviesBouldin | quote }} # Corrected to .Values.config.daviesBouldin
  SCORE_WEIGHT_CALINSKI_HARABASZ: {{ printf "%v" .Values.config.calinskiHarabasz | quote }}

  TOP_K_MOODS_FOR_PURITY_CALCULATION: {{ printf "%v" .Values.config.topKMoodsForPurityCalculation | quote }}

  # Statistics for Raw Score Scaling (Mood Diversity and Purity)
  LN_MOOD_DIVERSITY_MIN: {{ printf "%v" .Values.config.lnMoodDiversityStats.min | quote }}
  LN_MOOD_DIVERSITY_MAX: {{ printf "%v" .Values.config.lnMoodDiversityStats.max | quote }}
  LN_MOOD_DIVERSITY_MEAN: {{ printf "%v" .Values.config.lnMoodDiversityStats.mean | quote }}
  LN_MOOD_DIVERSITY_SD: {{ printf "%v" .Values.config.lnMoodDiversityStats.sd | quote }}

  LN_MOOD_DIVERSITY_EMBEDDING_MIN: {{ printf "%v" .Values.config.lnMoodDiversityEmbeddingStats.min | quote }}
  LN_MOOD_DIVERSITY_EMBEDDING_MAX: {{ printf "%v" .Values.config.lnMoodDiversityEmbeddingStats.max | quote }}
  LN_MOOD_DIVERSITY_EMBEDDING_MEAN: {{ printf "%v" .Values.config.lnMoodDiversityEmbeddingStats.mean | quote }}
  LN_MOOD_DIVERSITY_EMBEDDING_SD: {{ printf "%v" .Values.config.lnMoodDiversityEmbeddingStats.sd | quote }}

  LN_MOOD_PURITY_MIN: {{ printf "%v" .Values.config.lnMoodPurityStats.min | quote }}
  LN_MOOD_PURITY_MAX: {{ printf "%v" .Values.config.lnMoodPurityStats.max | quote }}
  LN_MOOD_PURITY_MEAN: {{ printf "%v" .Values.config.lnMoodPurityStats.mean | quote }}
  LN_MOOD_PURITY_SD: {{ printf "%v" .Values.config.lnMoodPurityStats.sd | quote }}

  LN_MOOD_PURITY_EMBEDDING_MIN: {{ printf "%v" .Values.config.lnMoodPurityEmbeddingStats.min | quote }}
  LN_MOOD_PURITY_EMBEDDING_MAX: {{ printf "%v" .Values.config.lnMoodPurityEmbeddingStats.max | quote }}
  LN_MOOD_PURITY_EMBEDDING_MEAN: {{ printf "%v" .Values.config.lnMoodPurityEmbeddingStats.mean | quote }}
  LN_MOOD_PURITY_EMBEDDING_SD: {{ printf "%v" .Values.config.lnMoodPurityEmbeddingStats.sd | quote }}

  # Statistics for Log-Transformed and Standardized "Other Features" Scores
  LN_OTHER_FEAT_DIV_MIN: {{ printf "%v" .Values.config.lnOtherFeaturesDiversityStats.min | quote }}
  LN_OTHER_FEAT_DIV_MAX: {{ printf "%v" .Values.config.lnOtherFeaturesDiversityStats.max | quote }}
  LN_OTHER_FEAT_DIV_MEAN: {{ printf "%v" .Values.config.lnOtherFeaturesDiversityStats.mean | quote }}
  LN_OTHER_FEAT_DIV_SD: {{ printf "%v" .Values.config.lnOtherFeaturesDiversityStats.sd | quote }}

  LN_OTHER_FEAT_PUR_MIN: {{ printf "%v" .Values.config.lnOtherFeaturesPurityStats.min | quote }}
  LN_OTHER_FEAT_PUR_MAX: {{ printf "%v" .Values.config.lnOtherFeaturesPurityStats.max | quote }}
  LN_OTHER_FEAT_PUR_MEAN: {{ printf "%v" .Values.config.lnOtherFeaturesPurityStats.mean | quote }}
  LN_OTHER_FEAT_PUR_SD: {{ printf "%v" .Values.config.lnOtherFeaturesPurityStats.sd | quote }}

  OTHER_FEATURE_PREDOMINANCE_THRESHOLD_FOR_PURITY: {{ printf "%v" .Values.config.otherFeaturePredominanceThresholdForPurity | quote }}

  # AI Playlist Naming
  OLLAMA_SERVER_URL: {{ .Values.config.ollamaServerUrl | quote }}
  OLLAMA_MODEL_NAME: {{ .Values.config.ollamaModelName | quote }}
  GEMINI_MODEL_NAME: {{ .Values.config.geminiModelName | quote }}

  # DB Host/Port/URL for Postgres and Redis (derived from service names)
  POSTGRES_HOST: {{ printf "%s-postgres" (include "audiomuse-ai.fullname" .) }}
  POSTGRES_PORT: {{ .Values.postgres.service.port | quote }}
  REDIS_URL: {{ printf "redis://%s-redis:%d/0" (include "audiomuse-ai.fullname" .) .Values.redis.service.port }}

  # AI User for Chat SQL Execution
  AI_CHAT_DB_USER_NAME: {{ .Values.config.aiChatDbUserName | quote }}

  # Classifier Constant
  TOP_N_OTHER_FEATURES: {{ printf "%v" .Values.config.topNOtherFeatures | quote }}

  # Energy Normalization Range
  ENERGY_MIN: {{ printf "%v" .Values.config.energyMin | quote }}
  ENERGY_MAX: {{ printf "%v" .Values.config.energyMax | quote }}

  # Tempo Normalization Range (BPM)
  TEMPO_MIN_BPM: {{ printf "%v" .Values.config.tempoMinBpm | quote }}
  TEMPO_MAX_BPM: {{ printf "%v" .Values.config.tempoMaxBPM | quote }}

  # Stratified Sampling Constants
  MIN_SONGS_PER_GENRE_FOR_STRATIFICATION: {{ printf "%v" .Values.config.minSongsPerGenreForStratification | quote }}
  STRATIFIED_SAMPLING_TARGET_PERCENTILE: {{ printf "%v" .Values.config.stratifiedSamplingTargetPercentile | quote }}
  SAMPLING_PERCENTAGE_CHANGE_PER_RUN: {{ printf "%v" .Values.config.samplingPercentageChangePerRun | quote }}

  # NOTE: JELLYFIN_USER_ID, JELLYFIN_TOKEN, POSTGRES_USER, POSTGRES_PASSWORD,
  # POSTGRES_DB, GEMINI_API_KEY, and AI_CHAT_DB_USER_PASSWORD are sourced
  # from Kubernetes Secrets, not the ConfigMap, as per your flask.yaml/worker.yaml.
  # MOOD_LABELS, TOP_N_MOODS, EMBEDDING_MODEL_PATH, PREDICTION_MODEL_PATH,
  # DANCEABILITY_MODEL_PATH, AGGRESSIVE_MODEL_PATH, HAPPY_MODEL_PATH,
  # PARTY_MODEL_PATH, RELAXED_MODEL_PATH, SAD_MODEL_PATH, OTHER_FEATURE_LABELS,
  # and STRATIFIED_GENRES are either hardcoded in config.py or derived from
  # other environment variables/internal logic and are not directly exposed
  # as individual environment variables from the ConfigMap based on config.py.