apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "audiomuse-ai.fullname" . }}-flask
  namespace: {{ .Release.Namespace }} # Use .Release.Namespace
  labels:
    {{- include "audiomuse-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: flask
spec:
  replicas: {{ .Values.flask.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "audiomuse-ai.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: flask
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "audiomuse-ai.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: flask
    spec:
      # Best Practice: Run as a non-root user for enhanced security.
      # The Docker image must be built to support this (e.g., by creating user 1001 and setting permissions).
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
        - name: flask-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "audiomuse-ai.fullname" . }}-env-vars
          env:
            - name: SERVICE_TYPE
              value: "flask"
            - name: JELLYFIN_USER_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "audiomuse-ai.fullname" . }}-jellyfin
                  key: user_id
            - name: JELLYFIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "audiomuse-ai.fullname" . }}-jellyfin
                  key: api_token
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "audiomuse-ai.fullname" . }}-postgres
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "audiomuse-ai.fullname" . }}-postgres
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "audiomuse-ai.fullname" . }}-postgres
                  key: POSTGRES_DB
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "audiomuse-ai.fullname" . }}-gemini
                  key: GEMINI_API_KEY
            - name: AI_CHAT_DB_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "audiomuse-ai.fullname" . }}-ai-chat-db
                  key: AI_CHAT_DB_USER_PASSWORD
          resources:
            {{- toYaml .Values.flask.resources | nindent 12 }}
          volumeMounts:
            - name: app-temp-audio
              mountPath: /app/temp_audio
      volumes:
        - name: app-temp-audio
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "audiomuse-ai.fullname" . }}-flask
  namespace: {{ .Release.Namespace }} # Use .Release.Namespace
  labels:
    {{- include "audiomuse-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: flask
spec:
  type: {{ .Values.flask.service.type }}
  ports:
    - port: {{ .Values.flask.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "audiomuse-ai.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: flask
