# Removed: apiVersion: v1, kind: Namespace, metadata: name: {{ .Values.namespace.name }}
# Helm will manage the namespace based on --namespace flag.

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "audiomuse-ai.fullname" . }}-jellyfin
  namespace: {{ .Release.Namespace }} # Use .Release.Namespace
  labels:
    {{- include "audiomuse-ai.labels" . | nindent 4 }}
type: Opaque
stringData:
  user_id: {{ .Values.jellyfin.userId | quote }}
  api_token: {{ .Values.jellyfin.token | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "audiomuse-ai.fullname" . }}-postgres
  namespace: {{ .Release.Namespace }} # Use .Release.Namespace
  labels:
    {{- include "audiomuse-ai.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  POSTGRES_DB: {{ .Values.postgres.db | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "audiomuse-ai.fullname" . }}-gemini
  namespace: {{ .Release.Namespace }} # Use .Release.Namespace
  labels:
    {{- include "audiomuse-ai.labels" . | nindent 4 }}
type: Opaque
stringData:
  GEMINI_API_KEY: {{ .Values.gemini.apiKey | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "audiomuse-ai.fullname" . }}-mistral
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "audiomuse-ai.labels" . | nindent 4 }}
type: Opaque
stringData:
  MISTRAL_API_KEY: {{ .Values.mistral.apiKey | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "audiomuse-ai.fullname" . }}-ai-chat-db
  namespace: {{ .Release.Namespace }} # Use .Release.Namespace
  labels:
    {{- include "audiomuse-ai.labels" . | nindent 4 }}
type: Opaque
stringData:
  AI_CHAT_DB_USER_PASSWORD: {{ .Values.postgres.aiChatDbUserPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "audiomuse-ai.fullname" . }}-navidrome
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "audiomuse-ai.labels" . | nindent 4 }}
type: Opaque
stringData:
  NAVIDROME_USER: {{ .Values.navidrome.user | quote }}
  NAVIDROME_PASSWORD: {{ .Values.navidrome.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "audiomuse-ai.fullname" . }}-lyrion
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "audiomuse-ai.labels" . | nindent 4 }}
type: Opaque
stringData:
  LYRION_USER: {{ .Values.lyrion.user | quote }}
  LYRION_PASSWORD: {{ .Values.lyrion.password | quote }}
