# .github/workflows/release-helm-chart.yml

name: Release Helm Chart

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: # Allow manual trigger

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.1
        with:
          version: 'v3.19.0'

      - name: Lint Helm Chart
        run: helm lint .

      - name: Get Chart Version
        id: chart_version
        run: |
          VERSION=$(grep '^version:' Chart.yaml | awk '{print $2}')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Chart version: $VERSION"

      - name: Package Helm Chart
        run: |
          helm package . --destination ./charts/
          ls -la ./charts/

      - name: Checkout gh-pages
        run: |
          git fetch origin gh-pages:gh-pages || git checkout --orphan gh-pages
          git checkout gh-pages

      - name: Update Helm Repository
        run: |
          # Copy the new chart package
          mkdir -p .
          cp ./charts/*.tgz . || echo "No new packages to copy"
          
          # Generate the index
          helm repo index . --url https://neptunehub.github.io/AudioMuse-AI-helm/
          
          # Show what we have
          echo "Files in gh-pages:"
          ls -la
          echo ""
          echo "Contents of index.yaml:"
          cat index.yaml

      - name: Commit and Push to gh-pages
        run: |
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Release chart version ${{ steps.chart_version.outputs.version }}"
            git push origin gh-pages
            echo "Successfully pushed to gh-pages"
          fi

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: ./charts/*.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
