# .github/workflows/release-helm-chart.yml

name: Release Helm Chart

on:
  push:
    branches:
      - main
      - devel
    tags:
      - 'v*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: '3.12.0'

      - name: Helm Lint
        run: helm lint .

  release:
    needs: lint
    permissions:
      contents: write
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: '3.12.0'

      # Remove the problematic cleanup step - let chart-releaser handle gh-pages
      # The force cleanup was likely causing issues

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: .
          skip_existing: false
          mark_as_latest: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Verify release was created
        run: |
          echo "Checking if release was created..."
          git fetch origin
          if git show-ref --verify --quiet refs/remotes/origin/gh-pages; then
            echo "gh-pages branch exists"
            git checkout gh-pages
            echo "Contents of gh-pages branch:"
            ls -la
            if [ -f "index.yaml" ]; then
              echo "SUCCESS: index.yaml found!"
              echo "Index.yaml contents:"
              cat index.yaml
            else
              echo "WARNING: index.yaml not found, but gh-pages branch exists"
            fi
          else
            echo "ERROR: gh-pages branch does not exist"
            echo "This usually means no chart was packaged and released"
            exit 1
          fi