release:
    needs: lint # This job will only run if the 'lint' job succeeds.
    # Grant permissions to create a GitHub Release and push to the gh-pages branch.
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetches all history for all branches and tags, which is required
          # by the chart-releaser action to determine changes.
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1 # Use the latest v1.x.y release
        with:
          charts_dir: .
          # The 'prerelease' input has been removed based on the error message.
          # If you need to mark a release as a pre-release on GitHub, you might need
          # to add a separate step using actions/create-release or manually
          # mark it on GitHub, or simply rely on chart versioning (e.g., 1.0.0-rc.1).
        env:
          # The chart-releaser action uses this token to create releases and push to gh-pages.
          # GITHUB_TOKEN is automatically provided by GitHub Actions.
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
