# .github/workflows/release-helm-chart.yml

name: Release Helm Chart

on:
  # This section defines when the workflow runs.
  # 'push' means it runs when code is pushed to the repository.
  push:
    # 'branches' specifies which branches will trigger the workflow on a push.
    branches:
      - main
      - devel
    # The 'paths' filter was removed as per your request to trigger on any change
    # when the chart is in the root directory.

# Ensures that only one workflow runs at a time for the same branch,
# cancelling any in-progress runs when a new one is triggered.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Helm Lint
        # Changed 'helm-chart' to '.' to lint from the root directory.
        run: helm lint .

  release:
    needs: lint # This job will only run if the 'lint' job succeeds.
    # Grant permissions to create a GitHub Release and push to the gh-pages branch.
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetches all history for all branches and tags, which is required
          # by the chart-releaser action to determine changes.
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1 # Use the latest v1.x.y release
        with:
          charts_dir: .
          # The 'prerelease' input was removed based on the previous error message.
        env:
          # The chart-releaser action uses this token to create releases and push to gh-pages.
          # GITHUB_TOKEN is automatically provided by GitHub Actions.
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
